apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: inventory-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: milanshub/inventory-client-demo:latest
          ports:
            - containerPort: 3000