apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: inventory-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: milanshub/inventory-server-demo:latest
          ports:
            - containerPort: 5000
          env:
           - name: MONGO_URI
             valueFrom:
               secretKeyRef:
                 name: mongo-secret
                 key: mongo_uri
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwt_secret
          - name: NODE_ENV
            value: production
          - name: PORT
            value: 5000
          - name: CORS_ORIGIN
            value: http://localhost:3000
            
          
