name: Node.js CI - Tests Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

 
    # Set up Node.js for the server (backend)
    - name: Setup Node.js for server
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Debugging: Check for server package-lock.json
    - name: Check server lock file
      run: |
        cd server
        ls -al  # This should show package-lock.json

    # Install server dependencies and run tests
    - name: Install and test server
      run: |
        cd server
        npm ci
        npm test
