name: Node.js CI - Tests Only

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Match local Node version
        cypress-version: [13.15.0] # Match local Cypress version

    steps:
      - uses: actions/checkout@v4

      # Clear Cache
      - name: Clear Webpack and Yarn Cache
        run: |
          rm -rf client/node_modules/.cache
          rm -rf client/node_modules
          yarn cache clean

      # Setup Node.js for Server
      - name: Setup Node.js for server
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: |
          cd server
          yarn install

      - name: Start server
        run: |
          cd server
          nohup yarn start &

      # Setup Node.js for Client
      - name: Setup Node.js for client
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install Client Dependencies
      - name: Install client dependencies
        run: |
          cd client
          yarn install
          yarn add cypress@${{ matrix.cypress-version }}

      - name: Start client
        run: |
          cd client
          nohup yarn start &

      # Wait for Server and Client
      - name: Wait for applications to be ready
        run: |
          until curl -s http://localhost:5000 > /dev/null; do echo "Waiting for server..."; sleep 5; done
          until curl -s http://localhost:3000 > /dev/null; do echo "Waiting for client..."; sleep 5; done

      # Debug - List Directory Structure
      - name: List client/src directory structure
        run: |
          cd client/src
          find . -type f

      # Print Environment Info
      - name: Print Node and Cypress Info
        run: |
          node -v
          npx cypress -v
          cd client
          cat cypress.config.js
          cat tsconfig.json

      # Run Cypress end-to-end tests
      - name: Run Cypress end-to-end tests
        run: |
          cd client
          yarn cypress:run:e2e
