name: Node.js CI - Tests Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js for the server (backend)
      - name: Setup Node.js for server
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install server dependencies and run tests with Yarn
      - name: Install and test server
        run: |
          cd server
          yarn install  # Install backend dependencies with Yarn
          yarn test     # Run backend tests with Yarn

      # Set up Node.js for the client (frontend)
      - name: Setup Node.js for client
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install client dependencies and run tests with Yarn
      - name: Install and test client
        run: |
          cd client
          yarn install  # Install frontend dependencies with Yarn
          yarn test     # Run frontend tests with Yarn
