name: Node.js CI - Tests Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Match the Node version you're using locally
        cypress-version: [13.15.0] # Match the Cypress version you're using locally

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Clear any existing cache to ensure a fresh run
      - name: Clear local cache and remove old files
        run: |
          rm -rf client/node_modules/.cache
          rm -rf client/node_modules
          yarn cache clean
          rm -f client/src/context/authContext.tsx
          rm -f client/src/components/errorBoundary.tsx

      # Set up Node.js for the server (backend)
      - name: Setup Node.js for server
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install server dependencies
      - name: Install server dependencies
        run: |
          cd server
          yarn install

      # Start server in the background
      - name: Start server
        run: |
          cd server
          nohup yarn start &

      # Set up Node.js for the client (frontend)
      - name: Setup Node.js for client
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install client dependencies and Cypress version
      - name: Install client dependencies
        run: |
          cd client
          yarn install
          yarn add cypress@${{ matrix.cypress-version }} # Explicitly install Cypress version

      # Start client in the background
      - name: Start client
        run: |
          cd client
          nohup yarn start &

      # Wait for the applications to be ready
      - name: Wait for applications to be ready
        run: |
          until curl -s http://localhost:5000 > /dev/null; do echo "Waiting for server..."; sleep 5; done
          until curl -s http://localhost:3000 > /dev/null; do echo "Waiting for client..."; sleep 5; done

      # Verify directory structure and file casing
      - name: Verify updated directory structure
        run: |
          cd client/src
          find . -type f | sort

      # Run Cypress component tests
      - name: Run Cypress component tests
        run: |
          cd client
          yarn cypress:run:component

      # Run Cypress end-to-end tests
      - name: Run Cypress end-to-end tests
        run: |
          cd client
          yarn cypress:run:e2e
